### ISSUE TITLE
Maximum number of selected points in query

### ISSUE THREAD

**Issue by FilipJanitor** [transceptor-technology/siridb-server#64]
Hi, I am currently testing your database. So far everything worked great and was really fast. Recently I needed to run one specific query and I got this message:

`Query has reached the maximum number of selected points (1000000). Please use another time windows, an aggregation function or select less series to reduce the number of points.`

I am estimating, that the query would work with ~180 million points, so one million is quite low limit for me. Is there some way how to configure this limit and increase it?  

Thanks in advance.

**Comment by joente** [comment]
Thank you for your comment. Currently this is a fixed-limit and the value of one million is just some arbitrary chosen number. It will not be so difficult to change this in a configurable value and I agree this would be a good idea. Probably a database property would be the best since we want every server in a siridb cluster to have the same limit for a given query. 

I think about the following statement for configuring the limit:
```
alter database set query_points_limit <number>
```

**Comment by joente** [comment]
Todo:

- [ ] update grammar
- [ ] create default values and store the values in database.dat
- [ ] auto migration at startup for old database.dat files
- [ ] make sure the correct limit values are synchronized when expanding with a new server
- [ ] check if each server is running the required version before processing the `set` statements
- [ ] create `show ...` statements for viewing the current values
- [ ] update siridb-prompt with new grammar
- [ ] update siridb-http with new grammar

**Comment by joente** [comment]
Released version 2.0.17 including this change.
